name: ragnarok_flutter
description: "Reuse components for GodHitech\\'s Flutter team"
version: 1.1.2

environment:
  sdk: ">=3.3.0 <4.0.0"
  flutter: 3.19.1

dependencies:
  cloud_firestore: any
  equatable: ^2.0.5
  firebase_analytics: any
  firebase_core: any
  firebase_crashlytics: any
  firebase_remote_config: any
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.5
  flutter_svg: ^2.0.10+1
  flutter_web_plugins:
    sdk: flutter
  google_mobile_ads: ^5.1.0
  in_app_review: ^2.0.9
  intl: ^0.19.0
  plugin_platform_interface: ^2.0.2
  shared_preferences: ^2.2.3
  flutter_easyloading: ^3.0.5
  flutter_screenutil: ^5.9.3
  url_launcher: ^6.3.0
  connectivity_plus: ^6.0.3
  app_tracking_transparency: ^2.0.5
  permission_handler: ^11.3.1
  flutter_local_notifications: ^17.1.2
  # flutter_timezone: ^1.0.8
  device_info_plus: ^10.1.0
  path_provider: ^2.1.3
  hive_flutter: ^1.1.0
  file_picker: ^8.0.5
  image_picker: ^1.1.2
  provider: ^6.1.2
  # android_path_provider: ^0.3.0
  # gma_mediation_meta: ^1.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true
  assets:
    - asset/
    - asset/icon/
    - asset/image/
  plugin:
    platforms:
      android:
        package: com.godhitech.flutter.ragnarok.ragnarok_flutter
        pluginClass: RagnarokFlutterPlugin
      ios:
        pluginClass: RagnarokFlutterPlugin
      linux:
        pluginClass: RagnarokFlutterPlugin
      macos:
        pluginClass: RagnarokFlutterPlugin
      windows:
        pluginClass: RagnarokFlutterPluginCApi
      web:
        pluginClass: RagnarokFlutterWeb
        fileName: ragnarok_flutter_web.dart
